site_name: Wallarm Documentation
site_url: https://docs.wallarm.com/
site_description: Wallarm Advanced WAF protects websites, APIs and microservices from OWASP Top 10, bots and application abuse with no manual rule configuration and ultra-low false positives.

repo_url: https://github.com/wallarm/product-docs-en
repo_name: GitHub

copyright: '<a href="https://wallarm.com/terms-of-services" target="_blank">Terms of services</a> | <a href="https://wallarm.com/privacy-policy" target="_blank">Privacy policy</a> | <a href="https://wallarm.com/cookie-policy" target="_blank">Cookie policy</a> | 2021 © Wallarm Inc.'

plugins:
  - search
  - minify:
      minify_html: true
  - meta-descriptions
dev_addr: '127.0.0.1:8000'

theme:
  name: material
  custom_dir: stylesheets
  features:
    - tabs
  logo: images/wallarm-logo-new.svg
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/github-alt
  font:
    text: Inter
    code: Roboto Mono
  version: "3.0"

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://wallarm.com
    - icon: fontawesome/brands/github-alt
      link: https://github.com/wallarm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wallarm
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/4871419
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCgD4zSzAJwf3tBlOgJo7Qkw

extra_css:
  - 'extra_new.css'

extra_javascript:
  - 'extra.js'

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums_style: table
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
      base_path: docs
  - nl2br
  - tables
  - sane_lists
  - attr_list
  - prependnewline
  - lightgallery:
      show_description_in_lightgallery: false
  - meta

google_analytics: ['UA-45499521-1', 'docs.wallarm.com']

docs_dir: docs/3.0
site_dir: site
edit_uri: ../product-docs-en/edit/master/docs/latest/

nav:
  - WAF guides:
    - Home: index.md
    - About Wallarm WAF:
        - What is Wallarm WAF: about-wallarm-waf/overview.md
        - Attack and vulnerability types: attacks-vulns-list.md
        - How Wallarm WAF works:
          - Wallarm WAF architecture: about-wallarm-waf/architecture.md
          - Detecting attacks: about-wallarm-waf/protecting-against-attacks.md
          - Detecting vulnerabilities: about-wallarm-waf/detecting-vulnerabilities.md
        - Wallarm WAF deployment options: admin-en/supported-platforms.md
        - Data management policies:
          - Security Model of Shared Responsibility for Customer Data: about-wallarm-waf/shared-responsibility.md
          - Data retention policy: about-wallarm-waf/data-retention-policy.md
        - Wallarm WAF subscription:
          - Wallarm WAF subscription plans: about-wallarm-waf/subscription-plans.md
          - Learning the amount of requests per month handled by the application: admin-en/operation/learn-incoming-request-number.md
    - Quickstart with WAF: quickstart-en/qs-install-node-en.md
    - Detailed WAF deployment guides:
      - NGINX:
        - Installing the WAF node as a dynamic module for NGINX stable: waf-installation/nginx/dynamic-module.md
        - Installing the WAF node as a dynamic module for NGINX from Debian/CentOS repositories: waf-installation/nginx/dynamic-module-from-distr.md
        - Installing the WAF node as a dynamic module for NGINX Plus: waf-installation/nginx-plus.md
      - Installing the WAF node on the Kong platform: admin-en/installation-kong-en.md
      - Cloud platforms:
        - Amazon AWS:
          - AWS Marketplace image deployment:
            - AWS Marketplace image deployment: admin-en/installation-ami-en.md
            - Configuring the WAF node autocaling on AWS: admin-en/installation-guides/amazon-cloud/autoscaling-overview.md
            - Example of deploying WAF Node on AWS using Terraform:
              - Introduction to using Terraform for the WAF node deployment: admin-en/installation-guides/amazon-cloud/deploy-waf-via-terraform/deploy-waf-via-terraform-intro.md
              - Quick Start with Provided Example: admin-en/installation-guides/amazon-cloud/deploy-waf-via-terraform/deploy-waf-via-terraform-quick-start.md
              - Description of Example Terraform Code: admin-en/installation-guides/amazon-cloud/deploy-waf-via-terraform/deploy-waf-via-terraform-code-desc.md
          - Deployment of the WAF node Docker image to AWS: waf-installation/cloud-platforms/aws/docker-container.md
          - Installation of the WAF node from DEB or RPM packages on AWS: waf-installation/cloud-platforms/aws/deb-rpm-packages.md
        - Google Cloud Platform:
          - GCP Marketplace image deployment:
            - GCP Marketplace image deployment: admin-en/installation-gcp-en.md
            - Configuring the WAF node autocaling on GCP: admin-en/installation-guides/google-cloud/autoscaling-overview.md
          - Deployment of the WAF node Docker image to GCP: waf-installation/cloud-platforms/gcp/docker-container.md
          - Installation of the WAF node from DEB or RPM packages on GCP: waf-installation/cloud-platforms/gcp/deb-rpm-packages.md
        - Microsoft Azure:
          - Deployment of the WAF node Docker image to Azure: waf-installation/cloud-platforms/azure/docker-container.md
          - Installation of the WAF node from DEB or RPM packages on Azure: waf-installation/cloud-platforms/azure/deb-rpm-packages.md
        - Alibaba Cloud:
          - Deployment of the WAF node Docker image to Alibaba Cloud: waf-installation/cloud-platforms/alibaba-cloud/docker-container.md
          - Installation of the WAF node from DEB or RPM packages on Alibaba Cloud: waf-installation/cloud-platforms/alibaba-cloud/deb-rpm-packages.md
        - Yandex.Cloud:
          - Yandex.Cloud Marketplace image deployment: admin-en/installation-guides/install-in-yandex-cloud.md
          - Deployment of the WAF node Docker image to Yandex.Cloud: waf-installation/cloud-platforms/yandex-cloud/docker-container.md
          - Installation of the WAF node from DEB or RPM packages on Yandex.Cloud: waf-installation/cloud-platforms/yandex-cloud/deb-rpm-packages.md
        - Deployment of the WAF node to the private clouds: waf-installation/cloud-platforms/private-cloud.md
      - Docker images:
        - Running Docker NGINX‑based image: admin-en/installation-docker-en.md
        - Running Docker Envoy‑based image: admin-en/installation-guides/envoy/envoy-docker.md
      - Kubernetes:
        - Deploying the NGINX-based WAF node as the K8s Ingress Controller: admin-en/installation-kubernetes-en.md
        - Installing Wallarm Sidecar Container:
          - How It Works: admin-en/installation-guides/kubernetes/wallarm-sidecar-container.md
          - Kubernetes Deployment Based on Helm Charts: admin-en/installation-guides/kubernetes/wallarm-sidecar-container-helm.md
          - Kubernetes Deployment Based on Manifests: admin-en/installation-guides/kubernetes/wallarm-sidecar-container-manifest.md
      - Separate postanalytics module installation: admin-en/installation-postanalytics-en.md
      - Deploying the partner WAF node: 
        - Partner scheme overview: partner-waf-node/overview.md
        - Creating and configuring a partner account: partner-waf-node/creating-partner-account.md
        - Creating and linking clients: partner-waf-node/connecting-clients.md
        - Installing and configuring a partner WAF node: partner-waf-node/installing-partner-waf-node.md
    - Basic configuration guides:
      - WAF node configuration files: admin-en/config-files.md
      - NGINX directives list: admin-en/configure-parameters-en.md
      - Envoy directives list: admin-en/configuration-guides/envoy/fine-tuning.md
      - Inress controller configuration parameters: admin-en/configure-kubernetes-en.md
      - Filtration mode configuration: admin-en/configure-wallarm-mode.md
      - Configuration of the blocking page and error code: admin-en/configuration-guides/configure-block-page-and-code.md
      - Allocating Resources for WAF Node: admin-en/configuration-guides/allocate-resources-for-waf-node.md
      - Splitting traffic processing by applications or environment: admin-en/split-by-apps.md
      - Cofiguring real IP reporting: admin-en/using-proxy-or-balancer-en.md
      - Configuring WAF node logging: admin-en/configure-logging.md
      - Configuring SELinux: admin-en/configure-selinux.md
      - WAF node and Wallarm Cloud synchronization configuration: admin-en/configure-cloud-node-synchronization-en.md
      - Configuring dynamic DNS resolution in NGINX: admin-en/configure-dynamic-dns-resolution-nginx.md
      - Monitoring & Failover:
        - Configuring a Failover Method: admin-en/configure-backup-en.md
        - Using a Mirrored Wallarm Repository:
          - How to Mirror the Wallarm Repository for CentOS: admin-en/integration-guides/repo-mirroring/centos/how-to-mirror-repo-artifactory.md
          - How to Install Wallarm Packages from the Local JFrog Artifactory Repository for CentOS: admin-en/integration-guides/repo-mirroring/centos/how-to-use-mirrored-repo.md
        - Monitoring the Filter Node:
          - Introduction to the WAF node monitoring: admin-en/monitoring/intro.md
          - How to Fetch Metrics: admin-en/monitoring/fetching-metrics.md
          - Available Metrics: admin-en/monitoring/available-metrics.md
          - Examples of Exporting and Working with Metrics:
            - Grafana:
              - Exporting Metrics to InfluxDB via the `collectd` Network Plugin: admin-en/monitoring/network-plugin-influxdb.md
              - Exporting Metrics to Graphite via the `collectd` Write Plugin: admin-en/monitoring/write-plugin-graphite.md
              - Working with the Filter Node Metrics in Grafana: admin-en/monitoring/working-with-grafana.md
            - Nagios:
              - Exporting Metrics to Nagios via the `collectd-nagios` Utility: admin-en/monitoring/collectd-nagios.md
              - Working with the Filter Node Metrics in Nagios: admin-en/monitoring/working-with-nagios.md
            - Zabbix:
              - Exporting Metrics to Zabbix via the `collectd-nagios` Utility: admin-en/monitoring/collectd-zabbix.md
              - Working with the Filter Node in Zabbix: admin-en/monitoring/working-with-zabbix.md        
    - Using Wallarm WAF:
      - Brute force protection: admin-en/configuration-guides/protecting-against-bruteforce.md
      - Events alerting and reporting:
        - Integrations:
          - Integrations Overview: user-guides/settings/integrations/integrations-intro.md 
          - Email Report: user-guides/settings/integrations/email.md
          - Slack: user-guides/settings/integrations/slack.md
          - Telegram: user-guides/settings/integrations/telegram.md
          - Opsgenie: user-guides/settings/integrations/opsgenie.md
          - InsightConnect: user-guides/settings/integrations/insightconnect.md
          - PagerDuty: user-guides/settings/integrations/pagerduty.md
          - Splunk: user-guides/settings/integrations/splunk.md
          - Sumo Logic: user-guides/settings/integrations/sumologic.md
          - Webhook:
            - Webhook Integration Overview: user-guides/settings/integrations/webhook.md
            - Examples:
              - IBM QRadar via Fluentd: user-guides/settings/integrations/webhook-examples/fluentd-qradar.md
              - IBM QRadar via Logstash: user-guides/settings/integrations/webhook-examples/logstash-qradar.md
              - Splunk Enterprise via Fluentd: user-guides/settings/integrations/webhook-examples/fluentd-splunk.md
              - Splunk Enterprise via Logstash: user-guides/settings/integrations/webhook-examples/logstash-splunk.md
              - Micro Focus ArcSight Logger via Fluentd: user-guides/settings/integrations/webhook-examples/fluentd-arcsight-logger.md
              - Micro Focus ArcSight Logger via Logstash: user-guides/settings/integrations/webhook-examples/logstash-arcsight-logger.md
        - Triggers:
          - Working with triggers: user-guides/triggers/triggers.md
          - Trigger examples: user-guides/triggers/trigger-examples.md
        - Creating a Custom Report: user-guides/search-and-filters/custom-report.md
      - Analyzing detected events:
        - Analyzing attacks: user-guides/events/analyze-attack.md
        - Analyzing vulnerabilities: user-guides/vulnerabilities/analyze-vuln.md
        - Using events search: user-guides/search-and-filters/use-search.md
        - Statistics on detected events: user-guides/dashboard/intro.md
      - Configuring custom ruleset:
        - Application Profile Rules: user-guides/rules/intro.md
        - Inspecting Application Profile Rules: user-guides/rules/view.md
        - Adding Rules in the Application Profile: user-guides/rules/add-rule.md
        - Building and unloading of a custom ruleset: user-guides/rules/compiling.md
        - Analyzing and Parsing Requests: user-guides/rules/request-processing.md
        - Filtration mode rule: user-guides/rules/wallarm-mode-rule.md
        - Rules for Data Masking: user-guides/rules/sensitive-data-rule.md
        - Rules defining attack counters: user-guides/rules/define-counters.md
        - Rewriting the request before attack replaying: user-guides/rules/change-request-for-active-verification.md
        - Virtual Patching: user-guides/rules/vpatch-rule.md
        - User‑Defined Detection Rules: user-guides/rules/regex-rule.md
      - Allowing access by IP addresses:
        - Types and core logic of IP lists: user-guides/ip-lists/overview.md
        - IP addresses whitelist: user-guides/ip-lists/whitelist.md
        - IP addresses greylist: user-guides/ip-lists/greylist.md
        - IP addresses blacklist: user-guides/ip-lists/blacklist.md
      - Using single sign‑on to Wallarm Console: user-guides/use-sso.md
      - Managing access to Wallarm Console: user-guides/settings/users.md
      - Using Wallarm Scanner: user-guides/scanner/intro.md
      - Audit log: user-guides/settings/audit-log.md
    - Updating and Migrating:
      - What is new in WAF node 3.0: updating-migrating/what-is-new.md
      - WAF node versioning policy: updating-migrating/versioning-policy.md
      - Recommendations for a safe WAF node update process: updating-migrating/general-recommendations.md
      - WAF node update instructions:
        - Updating Linux WAF packages: updating-migrating/nginx-modules.md
        - Updating the separately installed postanalytics module: updating-migrating/separate-postanalytics.md
        - Updating the running Docker NGINX- or Envoy-based image: updating-migrating/docker-container.md
        - Updating NGINX Ingress controller with integrated Wallarm WAF: updating-migrating/ingress-controller.md
        - Updating the cloud WAF node image: updating-migrating/cloud-image.md
      - Migrating whitelists and blacklists from previous WAF node versions to 3.0: updating-migrating/migrate-ip-lists-to-node-3.md
  - Glossary: glossary-en.md
  - API Firewall guides:
    - Wallarm API Firewall overview: api-firewall/overview.md
    - Running API Firewall on Docker: api-firewall/installation-guides/docker-container.md
    - Demos:
      - Running the example application and API Firewall with Docker Compose: api-firewall/demos/docker-compose.md
  - Wallarm API:
    - Wallarm API overview: api/overview.md
    - Wallarm API request examples: api/request-examples.md 
  - FAQ:
    - Compatibility of Wallarm WAF with NGINX versions: faq/waf-nginx-compatibility.md
    - Deploying WAF Node in AWS Using Terraform: faq/waf-aws-via-terraform-installation.md 
    - Installing Wallarm WAF Ingress controller: faq/waf-ingress-installation.md
    - Errors after Wallarm WAF installation: faq/common-errors-after-waf-installation.md
    - Wallarm service status page: faq/wallarm-status-page.md
  - Demo videos:
    - Wallarm WAF overview and deployment options: demo-videos/waf-overview.md
    - Inspecting events detected by the Wallarm WAF node: demo-videos/waf-events-inspection.md
    - Wallarm Scanner overview: demo-videos/scanner-overview.md
    - Notifications and reactions to events detected by Wallarm WAF: demo-videos/notifications.md
    - Wallarm FAST overview and integration options: demo-videos/fast-overview.md
